# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from traj_utils/polynomial.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class polynomial(genpy.Message):
  _md5sum = "fc5028b9e68e7966d83027aa556694ff"
  _type = "traj_utils/polynomial"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 drone_id
int32 traj_id
time start_time
float64 totalDuration
int16 pieceNum
uint8 order
float64[] Duration
float64[] Xcoeff
float64[] Ycoeff
float64[] Zcoeff
bool captured
"""
  __slots__ = ['drone_id','traj_id','start_time','totalDuration','pieceNum','order','Duration','Xcoeff','Ycoeff','Zcoeff','captured']
  _slot_types = ['int16','int32','time','float64','int16','uint8','float64[]','float64[]','float64[]','float64[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       drone_id,traj_id,start_time,totalDuration,pieceNum,order,Duration,Xcoeff,Ycoeff,Zcoeff,captured

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(polynomial, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.drone_id is None:
        self.drone_id = 0
      if self.traj_id is None:
        self.traj_id = 0
      if self.start_time is None:
        self.start_time = genpy.Time()
      if self.totalDuration is None:
        self.totalDuration = 0.
      if self.pieceNum is None:
        self.pieceNum = 0
      if self.order is None:
        self.order = 0
      if self.Duration is None:
        self.Duration = []
      if self.Xcoeff is None:
        self.Xcoeff = []
      if self.Ycoeff is None:
        self.Ycoeff = []
      if self.Zcoeff is None:
        self.Zcoeff = []
      if self.captured is None:
        self.captured = False
    else:
      self.drone_id = 0
      self.traj_id = 0
      self.start_time = genpy.Time()
      self.totalDuration = 0.
      self.pieceNum = 0
      self.order = 0
      self.Duration = []
      self.Xcoeff = []
      self.Ycoeff = []
      self.Zcoeff = []
      self.captured = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hi2IdhB().pack(_x.drone_id, _x.traj_id, _x.start_time.secs, _x.start_time.nsecs, _x.totalDuration, _x.pieceNum, _x.order))
      length = len(self.Duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.Duration))
      length = len(self.Xcoeff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.Xcoeff))
      length = len(self.Ycoeff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.Ycoeff))
      length = len(self.Zcoeff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.Zcoeff))
      _x = self.captured
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.drone_id, _x.traj_id, _x.start_time.secs, _x.start_time.nsecs, _x.totalDuration, _x.pieceNum, _x.order,) = _get_struct_hi2IdhB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Duration = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Xcoeff = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Ycoeff = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Zcoeff = s.unpack(str[start:end])
      start = end
      end += 1
      (self.captured,) = _get_struct_B().unpack(str[start:end])
      self.captured = bool(self.captured)
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hi2IdhB().pack(_x.drone_id, _x.traj_id, _x.start_time.secs, _x.start_time.nsecs, _x.totalDuration, _x.pieceNum, _x.order))
      length = len(self.Duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.Duration.tostring())
      length = len(self.Xcoeff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.Xcoeff.tostring())
      length = len(self.Ycoeff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.Ycoeff.tostring())
      length = len(self.Zcoeff)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.Zcoeff.tostring())
      _x = self.captured
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.drone_id, _x.traj_id, _x.start_time.secs, _x.start_time.nsecs, _x.totalDuration, _x.pieceNum, _x.order,) = _get_struct_hi2IdhB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Duration = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Xcoeff = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Ycoeff = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Zcoeff = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 1
      (self.captured,) = _get_struct_B().unpack(str[start:end])
      self.captured = bool(self.captured)
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_hi2IdhB = None
def _get_struct_hi2IdhB():
    global _struct_hi2IdhB
    if _struct_hi2IdhB is None:
        _struct_hi2IdhB = struct.Struct("<hi2IdhB")
    return _struct_hi2IdhB
